baseURL = 'https://andrewqie.github.io/myblog/'
languageCode = 'en-us'
title = 'Unfiltered Musings: Thoughts, Reflections, and Rants...'
theme = 'paper'
[params]
    # color style
    color = 'linen'

    # home page profile
    name = 'Andrew Qie'
    bio = '还在读书的中年男性，已婚，育有一儿一女'

    # header social icons
    instagram = 'andreasq86'           # instagram.com/andreasq86
