baseURL = 'https://andrewqie.github.io/myblog/'
languageCode = 'en-us'
title = 'Unfiltered Musings: Thoughts, Reflections, and Rants...'
theme = 'paper'
[params]
    # color style
    color = 'linen'
    
    # header social icons
    instagram = 'andreasq86'           # instagram.com/andreasq86
