baseURL = 'https://andrewqie.github.io/myblog/'
languageCode = 'en-us'
title = 'Unfiltered Musings'
theme = 'archie'
timeZone = 'America/New_York'
paginate = 5 # articles per page
copyright = '© Andrewqie'

[params]
    
    subtitle = 'Thoughts, Reflections, and Rants...'
    googleAnalytics = "G-FCB40SPT6E"
    mode = "auto"

[[menu.main]]
    name = "All posts"
    url = "/posts"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 3
